include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    avoid_print: true
    prefer_const_literals_to_create_immutables: true
    unnecessary_null_in_if_null_operators: true
    unawaited_futures: true
    await_only_futures: true

